version: '3'
services:
  mysql: 
    image: mysql:8
    container_name: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=pass 
      - LANG=C.UTF-8 
    ports: 
      - 3306:3306 
    volumes: 
      - ./tmp/mysql:/var/lib/mysql 