name: Publish release

on:
  workflow_dispatch:
  push:
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build-scanner:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: scanner
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: |
          yarn
          yarn gen
          yarn build
      - name: Get tag
        id: get_tag
        shell: bash
        run: |
          tag=${GITHUB_REF##*/}
          if [[ "$tag" =~ [0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "::set-output name=tag::sigoden/subexpo-scanner:latest,sigoden/subexpo-scanner:$tag"
          else
            echo "::set-output name=tag::sigoden/subexpo-scanner:dev"
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.get_tag.outputs.tag }}

  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: |
          yarn
          yarn gen
          yarn build
      - name: Get tag
        id: get_tag
        shell: bash
        run: |
          tag=${GITHUB_REF##*/}
          if [[ "$tag" =~ [0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "::set-output name=tag::sigoden/subexpo-ui:latest,sigoden/subexpo-ui:$tag"
          else
            echo "::set-output name=tag::sigoden/subexpo-ui:dev"
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.get_tag.outputs.tag }}